Repository SUIN-BUNDANG-LINE/Backend, pull requests merged in 2024-09, with the labels that each got.

#55 [SBL-106] 여러 상황별 리디렉션 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2User.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/CookieUtils.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/LoginController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/LoginApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/dto/DefaultUserProfile.kt
Labels: 오류수정, 기능구현

#56 [SBL-110] 추첨 방식 선택 기능, 설문 공개 여부 설정 기능 추가
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/ByUserRewardInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/ImmediateDrawRewardInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyParticipantResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidRewardInfoException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingBoardFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardInfoTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardTest.kt
Labels: 기능구현

#57 [SBL-118] createdAt 컬럼이 매번 업데이트되던 오류 수정
  src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingBoardAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/adapter/UserAdapter.kt
Labels: 오류수정

#58 [SBL-111] 단순 설문 결과 조회 API 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResultController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResultApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResult.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ResponseDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ResponseRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResultService.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyResultTest.kt
Labels: 기능구현

#59 [SBL-120] visitorId관련 코드 삭제
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/fingerprint/FingerprintApi.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/fingerprint/UncleanVisitorException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Participant.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ParticipantRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/LoginApiDoc.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/ParticipantTest.kt
Labels: 기능제거

#60 [SBL-123] 설문 결과 조회 API에 응답에 따른 필터링 기능 추가
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResultController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResultApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/QuestionFilter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultDetails.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultFilter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResult.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResultRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidQuestionFilterException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidResultDetailsException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResultService.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyResultConstFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyResultTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/QuestionResultDetailsTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultFilterTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResultTest.kt
Labels: 기능구현

#61 [SBL-137] 리워드 지급 설정 정보 관련 기능 수정
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/ByUserRewardInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/FinishedAt.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/ImmediateDrawSetting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/NoRewardSetting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardSetting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardSettingType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/reward/SelfManagementSetting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidFinishedAtException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidRewardSettingException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardInfoTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/reward/RewardSettingTest.kt
Labels: 기능구현

#63 [SBL-133] s3 upload
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/aws/controller/S3Controller.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/controller/doc/S3ApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/dto/request/S3UploadRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/dto/response/S3UploadResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/exception/FileNameTooLongException.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/exception/FileNameTooShortException.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/exception/InvalidExtensionException.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/exception/NoExtensionExistException.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/exception/NoFileExistException.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/exception/OutOfFileSizeException.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/service/S3Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/S3Config.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/FileValidator.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/LoginController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/LoginApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/UserApiDoc.kt
  src/main/resources/application.yml
Labels: 기능구현

#64 [SBL-119] 마이페이지 설문 목록 조회 API 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/MySurveySortType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/MyPageSurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/MyPageSurveysResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepositoryImpl.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
Labels: 기능구현

#66 [SBL-139] 설문 제작 AI 서버로의 요청 API 구현
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/GenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/GenerateAPIDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/QuestionGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/SectionGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/SurveyGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerateRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/FileExtensionNotSupportedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/FileNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/SurveyGenerationByAIFailedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/TextTooLongException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/aws/service/S3Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RestTemplateConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/UserFileManagementConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/PythonServerExceptionMapper.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/RandomNicknameGenerator.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/FileNameTooLongException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/FileNameTooShortException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/InvalidExtensionException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/InvalidFileUrlException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/NoExtensionExistException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/NoFileExistException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/OutOfFileSizeException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/validator/FileUploadValidator.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/validator/FileUrlValidator.kt
  src/main/resources/application.yml
Labels: 기능구현

#68 [SBL-148] 설문 결과 API를 클라이언트 요구사항에 맞게 수정, 선택지와 필터에 개수 제한 추가
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/choice/Choices.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/QuestionResult.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultDetails.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultFilter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResult.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidResultFilterException.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyResultConstFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoicesTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/result/ResultFilterTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/result/SurveyResultTest.kt
Labels: 기능구현

#70 [SBL-146] 참가자 목록 API 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyParticipantController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyParticipantApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Participant.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/ParticipantsInfoListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ParticipantRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyParticipantService.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/ParticipantTest.kt
Labels: 기능구현

#69 [SBL-150] object class로의 리팩터링
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/RandomNicknameGenerator.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/ResetSession.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/SessionRegistryCleaner.kt
  src/main/resources/application.yml
Labels: 리팩토링

#72 [SBL-161] AI 컨트롤러 request 변경
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/GenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/GenerateAPIDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/QuestionGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithFileUrlRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithTextDocumentRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
Labels: 기능구현

#73 [SBL-157] 설문 종료 API 구현, 설문 결과 API 참가자 수 로직 수정
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResultService.kt
Labels: 오류수정, 기능구현
