Repository SUIN-BUNDANG-LINE/Backend, pull requests merged in 2024-10, with the labels that each got.

#74 [SBL-165] MongoDB 스키마 버전 관리를 위한 Mongock 초기 세팅
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/global/config/MongockConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/migration/InitialMongoDBSetUp.kt
  src/main/resources/application.yml
Labels: 환경설정

#75 [SBL-131] 설문 삭제 API 구현, softDelete 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/migration/AddIsDeletedFieldAtSurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepositoryImpl.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
Labels: 기능구현

#76 [SBL-130] 설문 종료 스케줄러 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SchedulingConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/scheduler/SurveyFinishScheduler.kt
Labels: 기능구현

#77 SBL-169 chat-session-id 쿠키 설정과 레디스 설정 추가
  docker-compose.yml
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/GenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIGenerateApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/ChatSessionIdWithSurveyGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyGenerationResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
Labels: 기능구현, 리팩토링

#78 [SBL-162] 핑거 프린트 정상화
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/FingerprintApi.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/exception/UncleanVisitorException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResponseApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Participant.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/AlreadyParticipatedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ParticipantRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/ParticipantTest.kt
Labels: 기능구현, 환경설정

#82 Hotfix: 쿠키 도메인 관련 설정 추가
  .github/workflows/prod_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
  src/main/resources/application.yml
Labels: 오류수정

#84 [SBL-177] request edit chat to python
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/ChatAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIChatController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIChatApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIGenerateApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/AIGeneratedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSection.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/ChatSessionIdWithSurveyGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/SectionGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/SurveyGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditQuestionRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditSectionRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditSurveyRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/GenerateSurveyResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/QuestionResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/SectionResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/SurveyResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/EditSurveyDataWithChatRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyEditResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyGenerationResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/ChatSessionIdCookieNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/InvalidModificationTargetId.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/repository/ChatRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/ChatService.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RestTemplateConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/PythonServerExceptionMapper.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
Labels: 기능구현, 리팩토링

#85 설문이용 v1.0.1 백엔드 배포
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/ChatAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIChatController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIChatApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIGenerateApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/AIGeneratedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSection.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/ChatSessionIdWithSurveyGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/SectionGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/SurveyGeneratedByAI.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditQuestionRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditSectionRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/EditSurveyRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/GenerateSurveyResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/QuestionResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/SectionResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/SurveyResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/EditSurveyDataWithChatRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyEditResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyGenerationResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/ChatSessionIdCookieNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/InvalidModificationTargetId.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/repository/ChatRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/ChatService.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RestTemplateConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/PythonServerExceptionMapper.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/CookieUtils.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
Labels: 배포

#86 HOTFIX: JSESSIONID의 domain을 ServletContextInitializer로 주입하도록 수정
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SessionConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/CookieUtils.kt
Labels: 배포

#89 [SBL-182] AI Chat을 이용한 수정 시 기존 설문과 수정된 설문의 변경사항 반환 & 초안 생성 시 surveyId 받기
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/ChatAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIGenerateApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/GenerateSurveyResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyEditResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/ChatService.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 기능구현

#90 [SBL-193] edit generated survey
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/AILogAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/ChatAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/AIEditLog.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSection.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/QuestionResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/SectionResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/SurveyResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/EditSurveyDataWithChatRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/entity/AIEditLogDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/AIEditLogNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/SurveyAIProcessingFailedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/repository/AIEditLogRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/repository/ChatRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/ChatService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/PythonServerExceptionMapper.kt
Labels: 기능구현

#91 [SBL-181] chatSessionId는 surveyId를 참조하도록 함
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIChatController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/AIGeneratedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/response/GenerateSurveyResponseFromPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithFileUrlRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithTextDocumentRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/response/AISurveyGenerationResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/ChatService.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
Labels: 기능구현, 기능제거

#93 [SBL-190] 인증을 세션 방식에서 JWT 방식으로 변경
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomLogoutSuccessHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/strategy/CustomExpiredSessionStrategy.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/strategy/CustomInvalidSessionStrategy.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/jwt/JwtTokenProvider.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/jwt/exception/InvalidRefreshTokenException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/CookieUtils.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/ResetSession.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/SessionRegistryCleaner.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/adapter/RefreshTokenAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/dto/DefaultUserProfile.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/dto/response/UserSessionsResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/entity/RefreshToken.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/repository/RefreshTokenRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/service/AdminService.kt
Labels: 기능구현, 환경설정

#94 [SBL-199] 설문 통계 공개 기능 구현
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSection.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/domain/PythonFormattedSurvey.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/annotation/NullableLoginUser.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/migration/AddIsResultOpenAtSurveys.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/resolver/NullableLoginUserArgumentResolver.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyParticipantController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResultController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyWorkbenchController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyParticipantApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResultApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyWorkbenchApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyParticipantService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResultService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyWorkbenchService.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 기능구현

#96 [SBL-207] 테스트를 위한 Fingerprint Mocking Server를 사용하는 설문 응답 API 구현
  .github/workflows/dev_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/global/util/FakeFingerprintApi.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/FakeSurveyResponseController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/FakeSurveyResponseApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/FakeSurveyResponseService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/service/DummyDataService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/RandomResponseGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/Probability.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/ProbabilityPicker.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomParticipantGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomQuestionGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomResponseGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSectionGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSurveyGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomUserGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomUtil.kt
Labels: 기능구현

#97 [SBL-209] 설문 목록 조회시 정렬 옵션 추가, 필터 추가, 기타 사항 수정
  src/main/kotlin/com/sbl/sulmun2yong/global/jwt/JwtAuthenticationFilter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySortType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyCustomRepositoryImpl.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomParticipantGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomResponseGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSectionGenerateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/util/dummy/RandomSurveyGenerateUtil.kt
Labels: 기능구현

#103 [SBL-218] fileUrl과 textDocument nullable
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithFileUrlRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithTextDocumentRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
Labels: 기능구현

#104 [SBL-219] 데모 AI 설문 초안 생성 API 구현
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/AIDemoCountRedisAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIGenerateApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/DemoSurveyGenerationWithFileUrlRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/AIDemoCountLimitException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RedisConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
Labels: 기능구현, 환경설정

#105 [SBL-223] 설문 결과의 raw data를 확인할 수 있는 api 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/choice/Choices.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyRawResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/ChoiceEmptyException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/ChoiceSizeExceedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoicesTest.kt
Labels: 기능구현

#106 설문이용 v1.2.0 백엔드 배포
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/AIDemoCountRedisAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/GenerateAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/AIGenerateController.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/controller/doc/AIGenerateApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithFileUrlRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/python/request/GenerateWithTextDocumentRequestToPython.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/DemoSurveyGenerationWithFileUrlRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/dto/request/SurveyGenerationWithFileUrlRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/AIDemoCountLimitException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/service/GenerateService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RedisConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/choice/Choices.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyRawResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/ChoiceEmptyException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/ChoiceSizeExceedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoicesTest.kt
Labels: 배포
