Repository SUIN-BUNDANG-LINE/Backend, pull requests merged in 2024-08, with the labels that each got.

#20 [S BL-56] 설문 도메인 리팩토링
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Section.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoiceQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/Choices.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/MultipleChoiceQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/Question.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/ResponseDetail.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/SingleChoiceQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/TextQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/TextResponseQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/choice/Choice.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/choice/Choices.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/impl/StandardMultipleChoiceQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/impl/StandardSingleChoiceQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/impl/StandardTextQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/response/QuestionResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/response/ResponseDetail.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/response/SectionResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/response/SurveyResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/NumericalOrderRouting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/RouteDetails.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/RoutingStrategy.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/RoutingType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SectionRouteConfigs.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SectionRouteType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SetByChoiceRouting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SetByUserRouting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/section/Section.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/section/SectionId.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/section/SectionIds.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyProgressInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSectionIdsException.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/QuestionFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/RoutingFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/SectionFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/QuestionFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/ResponseFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/RoutingFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SectionFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyConstFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SectionIdTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SectionTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoiceTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoicesTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/QuestionResponseTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/QuestionTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/routing/RouteDetailsTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/routing/RoutingStrategyTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SectionRouteConfigsTest.kt
Labels: 테스트, 리팩토링

#21 [SBL-71] 추첨 패키지 리팩터링
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingMachine.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/drawingResult/DrawingResult.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/HasQuarterState.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/NoQuarterState.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/NonWinnerState.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/OpenTicketState.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/OutOfTicketState.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/State.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/WinnerState.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/ticket/NonWinningTicket.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/ticket/Ticket.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/ticket/WinningTicket.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/NonWinnerDrawingResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/WinnerDrawingResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingBoardDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistoryTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/StateTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingBoardFixtureFactory.kt
Labels: 리팩토링

#24 [SBL-46] Drawing History
  src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistory.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistoryGroup.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/DrawingHistoryDTOGroupedBySurveyId.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryGroupListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryGroupResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/exception/InvalidDrawingHistoryException.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/repository/DrawingHistoryRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/service/AdminService.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistoryTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingHistoryFixtureFactory.kt
Labels: 기능구현, 리팩토링

#25 [SBL-74] 배포 전 기타 사항 추가
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/SurveyCreateRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/SurveyCreateResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/SurveyClosedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
Labels: 기능구현, 환경설정

#26 설문이용 백엔드 1차 배포 수정본
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistory.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistoryGroup.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/DrawingHistoryDTOGroupedBySurveyId.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryGroupListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryGroupResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingHistoryResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/exception/InvalidDrawingHistoryException.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/repository/DrawingHistoryRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/SurveyCreateRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/SurveyCreateResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/SurveyClosedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/service/AdminService.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistoryTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingHistoryFixtureFactory.kt
Labels: 배포

#27 설문이용 백엔드 1차 배포 2차 수정본
  src/main/kotlin/com/sbl/sulmun2yong/Sulmun2yongApplication.kt
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
Labels: 배포

#30 [SBL-76] CI 파이프라인에서 SonarQube 코드 분석 대신 Jacoco 커버리지 리포트만 넣도록 수정
  .github/workflows/pull-request-ci.yml
  sonar-project.properties
Labels: 환경설정

#31 [S BL-75] New Relic APM 세팅
  .github/workflows/prod_deploy.yml
  build.gradle.kts
Labels: 환경설정

#32 운영서버 APM 적용
  .github/workflows/prod_deploy.yml
  .github/workflows/pull-request-ci.yml
  build.gradle.kts
  sonar-project.properties
  src/main/resources/application.yml
Labels: 배포

#34 [SBL-53] 설문 생성 API 구현 및 기타 사항 수정
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/annotation/LoginUser.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/resolver/LoginUserArgumentResolver.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/section/Section.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyCreateResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveySaveResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/UserApiDoc.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 기능구현

#36 Swagger 오류 해결 및 일부 변경사항 반영
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/annotation/LoginUser.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/resolver/LoginUserArgumentResolver.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/section/Section.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyCreateResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveySaveResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/UserApiDoc.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 오류수정, 배포

#35 [SBL-68] 설문 제작 정보 API 구현, 설문 저장 API 수정
  .github/workflows/pull-request-ci.yml
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingBoardFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
Labels: 기능구현

#38 [SBL-79] forwardedHeaderFilter 추가
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
Labels: 기능구현

#39 [SBL-79] forwardedHeaderFilter 추가
  .github/workflows/pull-request-ci.yml
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingBoardFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/survey/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
Labels: 배포

#37 [SBL-80] 설문 저장 API 구현, 설문 제작 정보 조회 및 저장 시 makerId 검사 추가
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/CustomAccessDeniedHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveySaveResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSurveyAccessException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidUpdateSurveyException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 기능구현

#40 [SBL-78] finger print config
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/fingerprint/FingerprintApi.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Participant.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/AlreadyParticipatedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ParticipantRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/main/resources/application.yml
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/ParticipantTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 기능구현, 환경설정

#41 [SBL-90] 배포 전 기타 수정사항 반영
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/global/annotation/IsAdmin.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/resolver/IsAdminArgumentResolver.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResponseApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
Labels: 기능구현

#42 [SBL-81] 설문 시작 API 구현
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/DateUtil.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyManagementController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyManagementApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSurveyStartException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 기능구현

#43 [SBL-91] CD 파이프라인 개선 작업 진행
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  build.gradle.kts
Labels: 환경설정

#44 [SBL-77] ssm action
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomLogoutSuccessHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/RandomNicknameGenerator.kt
Labels: 기능구현

#52 v0.1.0 백엔드 배포 수정본
  .github/workflows/dev_deploy.yml
  .github/workflows/prod_deploy.yml
Labels: 배포

#53 [SBL-103] finger print api 부정한 접근 감지 알고리즘
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/fingerprint/FingerprintApi.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/fingerprint/UncleanVisitorException.kt
Labels: 기능구현

#54 [SBL-98] 설문 저장, 설문 제작 정보 API 형식 수정
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySaveRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyMakeInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyManagementService.kt
Labels: 오류수정
