Repository SUIN-BUNDANG-LINE/Backend, pull requests merged in 2024-07, with the labels that each got.

#3 [SBL-21] 공통 응답 객체 및 에러 헨들러 구현
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/demo/controller/DemoController.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/controller/doc/DemoApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/dto/request/DemoCreateRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/dto/response/DemoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/entity/Demo.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/exception/DemoNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/service/DemoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/BusinessException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/response/ApiResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/response/SuccessCode.kt
Labels: 환경설정

#5 [SBL-28] 설문 목록 조회 API 구현
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/demo/controller/DemoController.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/controller/doc/DemoApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/dto/request/DemoCreateRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/dto/response/DemoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/entity/Demo.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/exception/DemoNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/repository/DemoRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/demo/service/DemoService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/MongoConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SwaggerConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/converter/BinaryToUUIDConverter.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/converter/UUIDToBinaryConverter.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/entity/BaseTimeDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/response/ApiResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/response/SuccessCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyStatus.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveySortType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/SurveyRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/main/resources/application.yml
Labels: 기능구현, 환경설정

#6 [SBL-38] CICD 수정
  .github/workflows/dev_deploy.yml
Labels: 환경설정

#8 [SBL-27] OAuth2 API, User API 구현
  .gitignore
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/frontend/controller/FrontendController.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/SecurityConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomLogoutSuccessHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2User.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/GoogleUserInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/KakaoUserInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/NaverUserInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/OAuth2UserInfo.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/Provider.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/exception/NaverAttributeCastingFailedException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/provider/exception/ProviderNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/strategy/CustomExpiredSessionStrategy.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/strategy/CustomInvalidSessionStrategy.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/RandomNicknameGenerator.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/ResetSession.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/SessionRegistryCleaner.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/adapter/UserAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/AdminController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/UserController.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/AdminApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/controller/doc/UserApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/domain/UserRole.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/dto/response/UserProfileResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/dto/response/UserSessionsResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/entity/UserDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/exception/InvalidUserException.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/exception/UserNotFoundException.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/repository/UserRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/service/AdminService.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/service/UserService.kt
  src/main/resources/application.yml
  src/main/resources/static/favicon.ico
  src/main/resources/templates/login.html
Labels: 기능구현, 환경설정

#9 [SBL-36] 설문 관련 도메인 클래스 구현 및 테스트 코드 작성
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Section.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/SectionResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/Choices.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/MultipleChoiceQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/Question.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/QuestionResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/QuestionType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/ResponseDetail.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/SingleChoiceQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/question/TextResponseQuestion.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/NumericalOrderRouting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/RouteDetails.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SectionRouteConfigs.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SectionRouteType.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SetByChoiceRouting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SetByUserRouting.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidChoiceException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidQuestionResponseException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidRewardException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSectionException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSectionResponseException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSectionRouteConfigsException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSurveyException.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidSurveyResponseException.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/QuestionFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/ResponseFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/RoutingFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/SectionFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/SurveyFixtureFactory.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/RewardTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SectionTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/ChoicesTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/QuestionResponseTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/question/QuestionTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/routing/RouteDetailsTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/routing/SectionRouteConfigsTest.kt
Labels: 테스트, 기능구현

#11 [SBL-42] 설문 진행 API 구현
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyInfoApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Survey.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyProgressInfoResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/SurveyDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyInfoService.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/SurveyTest.kt
Labels: 기능구현

#12 [SBL-52] 설문 응답 API 구현
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/doc/SurveyResponseApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/domain/Participant.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/request/SurveyResponseRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyParticipantResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ResponseDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ParticipantRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/repository/ResponseRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/service/SurveyResponseService.kt
  src/test/kotlin/com/sbl/sulmun2yong/survey/domain/ParticipantTest.kt
Labels: 기능구현

#13 [SBL-61] ktlint 포매팅 에러 수정 및 PR 제출 시 스타일을 검사하는 workflow 추가
  .editorconfig
  .github/workflows/check-ktlint-ci.yml
  .github/workflows/dev_deploy.yml
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ResponseAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyInfoController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/controller/SurveyResponseController.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/dto/response/SurveyListResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/domain/UserRole.kt
Labels: 오류수정, 환경설정

#15 [SBL-63] Jacoco 추가, PR 작성 시 SonarQube 분석 후 Commant 작성하도록 CI 파이프라인 작성
  .github/workflows/pull-request-ci.yml
  build.gradle.kts
  sonar-project.properties
Labels: 환경설정

#16 [SBL-65] 추첨 API 그리고 추첨 기록 도메인과 레포지토리 구현
  src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingBoardAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/controller/DrawingBoardController.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/controller/doc/DrawingBoardApiDoc.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingBoard.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistory.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/Reward.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/TicketFactory.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/state/OpenTicketState.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/ticket/NonWinningTicket.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/ticket/Ticket.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/ticket/WinningTicket.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/request/DrawingRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingBoardResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/DrawingResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/NonWinnerDrawingResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/response/WinnerDrawingResultResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingBoardDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/exception/AlreadyParticipatedDrawingException.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/exception/FinishedDrawingException.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/repository/DrawingBoardRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/repository/DrawingHistoryRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/ParticipantAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/adapter/SurveyAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/entity/ParticipantDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/survey/exception/InvalidParticipantException.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/BoardMakingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/domain/StateTest.kt
  src/test/kotlin/com/sbl/sulmun2yong/fixture/drawing/DrawingBoardFixtureFactory.kt
Labels: 기능구현

#17 [SBL-70] reward api에 전화번호 도입
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/drawing/adapter/DrawingHistoryAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/controller/DrawingBoardController.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/domain/DrawingHistory.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/dto/request/DrawingRequest.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/entity/DrawingHistoryDocument.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/repository/DrawingHistoryRepository.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/frontend/controller/FrontendController.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/WebMvcConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/data/PhoneNumber.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/data/exception/InvalidPhoneNumberException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/domain/User.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/dto/response/UserProfileResponse.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/entity/UserDocument.kt
  src/main/resources/static/favicon.ico
  src/main/resources/templates/login.html
Labels: 오류수정

#18 [SBL-69] user profile cookie
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2Service.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/CustomOAuth2User.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/oauth2/handler/CustomAuthenticationSuccessHandler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/util/ResetSession.kt
  src/main/kotlin/com/sbl/sulmun2yong/user/dto/DefaultUserProfile.kt
Labels: 기능구현

#19 [SBL-65] reward drawing
  src/main/kotlin/com/sbl/sulmun2yong/drawing/controller/DrawingBoardController.kt
  src/main/kotlin/com/sbl/sulmun2yong/drawing/controller/doc/DrawingBoardApiDoc.kt
Labels: 오류수정
