Repository SUIN-BUNDANG-LINE/Backend, pull requests merged in 2025-04, with the labels that each got.

#115 [SBL-236] AI_SERVER_BASE_URL 수정
  .github/workflows/prod_deploy.yml
Labels: 환경설정

#116 설문이용 v1.3.1 백엔드 배포
  .github/workflows/prod_deploy.yml
Labels: 배포

#117 [SBL-237] AI 서버 cold start 문제 해결을 위한 AI Warm Up 스케줄러 구현
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/AIHealthCheckFailException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/scheduler/AIWarmUpScheduler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
Labels: 기능구현

#118 설문이용 v1.3.2 백엔드 배포
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/exception/AIHealthCheckFailException.kt
  src/main/kotlin/com/sbl/sulmun2yong/ai/scheduler/AIWarmUpScheduler.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
Labels: 배포

#119 HOTFIX: API 응답 형식을 String으로 수정
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
Labels: 오류수정, 배포

#121 [SBL-238] AI Server 연결 설정 수정
  .github/workflows/prod_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RestTemplateConfig.kt
Labels: 환경설정

#122 설문이용 v1.3.3 백엔드 배포
  .github/workflows/prod_deploy.yml
  src/main/kotlin/com/sbl/sulmun2yong/ai/adapter/HealthCheckAdapter.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RestTemplateConfig.kt
Labels: 배포

#123 [SBL-240] 로그 용량을 줄이기 위해 일부 예외의 StackTrace 로깅을 제거
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/GlobalExceptionHandler.kt
Labels: 환경설정

#124 설문이용 v1.3.4 백엔드 배포
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/GlobalExceptionHandler.kt
Labels: 배포

#125 [SBL-241] Redis를 활용한 분산락을 통해 추첨 동시성 문제 해결
  build.gradle.kts
  src/main/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardService.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/config/RedissonConfig.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/error/ErrorCode.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/lock/DrawingLockKeyResolver.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/lock/RedissonLock.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/lock/RedissonLockAspect.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/lock/exception/InvalidLockKeyExpressionException.kt
  src/main/kotlin/com/sbl/sulmun2yong/global/lock/exception/TooManyLockRequestException.kt
  src/test/kotlin/com/sbl/sulmun2yong/drawing/service/DrawingBoardServiceConcurrencyTest.kt
Labels: 기능구현, 환경설정
